# Exercise 2#

## Task 1 ##


a) Tokenize the sentences in fileyelp_polarity.txt, removing punctuation.

In [28]:
import string
import collections, functools, operator 
import pandas as pd
import numpy as np
import os

def read_file(filename):
    df = pd.read_csv(filename, sep="\t", header=None)
    df = df.assign(tokens =df[0].apply(lambda x : x.translate(str.maketrans('', '', string.punctuation)).lower().split()))
    return df

df = read_file("yelp_polarity.txt")
display(df)

0  1  \
0                             Wow... Loved this place.  1   
1                                   Crust is not good.  0   
2            Not tasty and the texture was just nasty.  0   
3    Stopped by during the late May bank holiday of...  1   
4    The selection on the menu was great and so wer...  1   
..                                                 ... ..   
995  I think food should have flavor and texture an...  0   
996                           Appetite instantly gone.  0   
997  Overall I was not impressed and would not go b...  0   
998  The whole experience was underwhelming, and I ...  0   
999  Then, as if I hadn't wasted enough of my life ...  0   

                                                tokens  
0                            [wow, loved, this, place]  
1                               [crust, is, not, good]  
2    [not, tasty, and, the, texture, was, just, nasty]  
3    [stopped, by, during, the, late, may, bank, ho...  
4    [the, selection, on, the, menu, was, great, an...  
..                                                 ...  
995  [i, think, food, should, have, flavor, and, te...  
996                        [appetite, instantly, gone]  
997  [overall, i, was, not, impressed, and, would, ...  
998  [the, whole, experience, was, underwhelming, a...  
999  [then, as, if, i, hadnt, wasted, enough, of, m...  

[1000 rows x 3 columns]

The file is read using pandas and saved in the dataframe df. A function is then applied to all of the sentences using the apply() funciton. The lambda-function used first removes punctuation, then applies lower() and split().

b) Calculate token and bigram counts

In [2]:
def tokens_to_token_freq(tokens):
    dictionary = dict.fromkeys(tokens)
    for i in list(dictionary):
        count = 0
        for j in tokens:
            if j==i:
                count += 1
        dictionary[i] = count
    return dictionary

def bigram_list(sent):
    bigrams=[]
    for i in range(0, len(sent) - 1):
        bigrams.append(sent[i] + ' ' + sent[i + 1])
    return bigrams

df = df.assign(bigrams = df["tokens"].apply(lambda x : dict.fromkeys(bigram_list(x))))
df = df.assign(token_count = df["tokens"].apply(lambda x : tokens_to_token_freq(x)))
df = df.assign(bigram_count = df["bigrams"].apply(lambda x : tokens_to_token_freq(x)))
display(df)

0  1  \
0                             Wow... Loved this place.  1   
1                                   Crust is not good.  0   
2            Not tasty and the texture was just nasty.  0   
3    Stopped by during the late May bank holiday of...  1   
4    The selection on the menu was great and so wer...  1   
..                                                 ... ..   
995  I think food should have flavor and texture an...  0   
996                           Appetite instantly gone.  0   
997  Overall I was not impressed and would not go b...  0   
998  The whole experience was underwhelming, and I ...  0   
999  Then, as if I hadn't wasted enough of my life ...  0   

                                                tokens  \
0                            [wow, loved, this, place]   
1                               [crust, is, not, good]   
2    [not, tasty, and, the, texture, was, just, nasty]   
3    [stopped, by, during, the, late, may, bank, ho...   
4    [the, selection, on, the, menu, was, great, an...   
..                                                 ...   
995  [i, think, food, should, have, flavor, and, te...   
996                        [appetite, instantly, gone]   
997  [overall, i, was, not, impressed, and, would, ...   
998  [the, whole, experience, was, underwhelming, a...   
999  [then, as, if, i, hadnt, wasted, enough, of, m...   

                                               bigrams  \
0    {'this place': None, 'wow loved': None, 'loved...   
1    {'not good': None, 'crust is': None, 'is not':...   
2    {'texture was': None, 'not tasty': None, 'just...   
3    {'may bank': None, 'steve recommendation': Non...   
4    {'the selection': None, 'great and': None, 'we...   
..                                                 ...   
995  {'think food': None, 'were lacking': None, 'fo...   
996  {'instantly gone': None, 'appetite instantly':...   
997  {'not impressed': None, 'and would': None, 'wo...   
998  {'next time': None, 'the whole': None, 'go to'...   
999  {'wound by': None, 'took to': None, 'bring the...   

                                           token_count  \
0        {'loved': 1, 'place': 1, 'wow': 1, 'this': 1}   
1           {'crust': 1, 'not': 1, 'good': 1, 'is': 1}   
2    {'tasty': 1, 'just': 1, 'nasty': 1, 'was': 1, ...   
3    {'steve': 1, 'it': 1, 'rick': 1, 'bank': 1, 'l...   
4    {'menu': 1, 'great': 1, 'was': 1, 'so': 1, 'se...   
..                                                 ...   
995  {'flavor': 1, 'i': 1, 'food': 1, 'were': 1, 't...   
996         {'instantly': 1, 'appetite': 1, 'gone': 1}   
997  {'i': 1, 'overall': 1, 'go': 1, 'impressed': 1...   
998  {'just': 1, 'i': 1, 'go': 1, 'was': 1, 'to': 1...   
999  {'salt': 1, 'my': 1, 'it': 1, 'to': 1, 'wasted...   

                                          bigram_count  
0    {'this place': 1, 'wow loved': 1, 'loved this'...  
1          {'not good': 1, 'crust is': 1, 'is not': 1}  
2    {'texture was': 1, 'not tasty': 1, 'just nasty...  
3    {'may bank': 1, 'steve recommendation': 1, 'an...  
4    {'the selection': 1, 'was great': 1, 'were the...  
..                                                 ...  
995  {'think food': 1, 'were lacking': 1, 'should h...  
996     {'instantly gone': 1, 'appetite instantly': 1}  
997  {'not impressed': 1, 'and would': 1, 'would no...  
998  {'next time': 1, 'underwhelming and': 1, 'the ...  
999  {'wound by': 1, 'took to': 1, 'bring the': 1, ...  

[1000 rows x 6 columns]

c) Print the 10 most frequent bigrams and their frequency

In [3]:
def frequency(column):
    frequency = dict(functools.reduce(operator.add, 
         map(collections.Counter, column)))
    frequency = sorted(frequency.items(), key=lambda x: x[1])
    return(list(frequency))

bigrams = frequency(df["bigram_count"])
print(bigrams[len(bigrams) - 10 : ])

[('on the', 23), ('the service', 24), ('service was', 26), ('and i', 27), ('of the', 29), ('food was', 32), ('and the', 38), ('it was', 41), ('the food', 47), ('this place', 72)]


d.) Print a bigram matrix from the 10 most frequent tokens

In [4]:
token_frequency = frequency(df["token_count"])

def bigram_matrix(token_list, bigram_frequencies):
    matrix = np.zeros((len(token_list), len(token_list)))
    for i in range(0, len(matrix)):
        for j in range(0, len(matrix)):
            key_str = token_list[i][0] + " " + token_list[j][0]
            bigram_frequencies = dict(bigram_frequencies)
            if key_str in bigram_frequencies:
                matrix[i, j] = bigram_frequencies[key_str]          
    return matrix

print(bigram_matrix(token_frequency[len(token_frequency) - 10 : ], bigrams))

[[ 0.  1.  4.  0.  0. 10.  0.  0.  0. 29.]
 [ 0.  0.  0. 10.  2.  1. 41.  2.  3.  0.]
 [ 0.  0.  0. 20.  1.  0. 10.  0.  0.  0.]
 [ 1.  0.  0.  0.  1. 16.  1.  0.  0. 10.]
 [ 0.  1.  2.  0.  0.  3.  0.  0.  1. 11.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 21.  0.  0.  0. 13.]
 [ 0.  0.  0.  0.  0.  0. 19.  0.  0.  0.]
 [ 0. 17.  4.  0.  0.  3.  5. 27.  0. 38.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


## Task 2

Using the code of Task 1:

a.) Extract top 20 most frequent bigrams of all positive and negative documents in folder polarity




In [41]:
pos_docs = os.listdir("./polarity/pos")
pos_df = read_file("./polarity/pos/" + pos_docs[0])
for doc in pos_docs[1:]:
    pos_df = pos_df.append(read_file("./polarity/pos/" + doc))

pos_df = pos_df.assign(bigrams = pos_df["tokens"].apply(lambda x : dict.fromkeys(bigram_list(x))))
pos_df = pos_df.assign(token_count = pos_df["tokens"].apply(lambda x : tokens_to_token_freq(x)))
pos_df = pos_df.assign(bigram_count = pos_df["bigrams"].apply(lambda x : tokens_to_token_freq(x)))

pos_bigrams = frequency(pos_df["bigram_count"])
print(pos_bigrams[len(pos_bigrams) - 20:])

neg_docs = os.listdir("./polarity/neg")
neg_df = read_file("./polarity/neg/" + neg_docs[0])
for doc in neg_docs[1:]:
    neg_df = neg_df.append(read_file("./polarity/neg/" + doc))

print(neg_df)
neg_df = neg_df.assign(neg_bigrams = neg_df["tokens"].apply(lambda x : dict.fromkeys(bigram_list(x))))
neg_df = neg_df.assign(token_count = neg_df["tokens"].apply(lambda x : tokens_to_token_freq(x)))
neg_df = neg_df.assign(bigram_count = neg_df["bigrams"].apply(lambda x : tokens_to_token_freq(x)))
# print(neg_df)
# neg_bigrams = frequency(neg_df["bigram_count"])
# print(neg_bigrams[len(neg_bigrams) - 20:])
# print(neg_df[0])

[('and his', 4), ('from a', 4), ('youve got', 4), ('and the', 5), ('the first', 5), ('the movie', 5), ('it is', 5), ('this film', 5), ('as the', 5), ('from the', 5), ('is a', 6), ('to be', 7), ('is the', 7), ('with a', 7), ('the film', 8), ('by the', 8), ('with the', 8), ('the shark', 9), ('of the', 14), ('in the', 24)]
                                                    0  \
0   synopsis : a mentally unstable man undergoing ...   
1   unsuccessfully attempting to gain the woman's ...   
2   comments : stalked is yet another in a seeming...   
3   their proliferation may be due in part to the ...   
4   stalked wavers slightly from the norm in one r...   
..                                                ...   
30  it also wrapped production two years ago and h...   
31                               whatever . . . skip    
32                                              it !    
33                       where's joblo coming from ?    
34  a nightmare of elm street 3 ( 7/10 ) - blair w.

KeyError: 'bigrams'

b.) Calculate their probability as aforementioned

c.) Write a script to save in a file the most probably bigrams of both classes and their probabilites separated by tabs

d.) Compare the output of both classes and write an analysis of your obersvations